### ISSUE TITLE
[Bug] Cannot load hf models

### ISSUE THREAD

**Issue by curiousjp** [neggles/wdv3-timm#3]
Hello -

I'm not sure if this is a quirk of my system, but here `timm.list_pretrained` returns a list of model names, and as such cannot be `.eval()`'d to produce a model object [on line 127 of wdv3_timm.py](https://github.com/neggles/wdv3-timm/blob/main/wdv3_timm.py?plain=1#L127). (It also returns an empty list even when an hf-hub: prefix is passed as the filter argument, at least from a cold install.) 

Should this line instead be `model: nn.Module = timm.create_model("hf-hub:" + repo_id, pretrained=True)` as described [in the timm examples on huggingface](https://huggingface.co/docs/hub/en/timm)?

**Comment by ProGamerGov** [comment]
@curiousjp Does `model: nn.Module = timm.create_model("hf-hub:" + repo_id, pretrained=True) ` work for you?

**Comment by neggles** [comment]
Yes, yes it should. I do not know how I missed that... Will fix, sorry for the delay!
